In [2]:
import tensorflow as tf
import numpy as np

In [4]:
n_inputs=3
n_neurons=5
X0=tf.placeholder(tf.float32,[None,n_inputs])
X1=tf.placeholder(tf.float32,[None,n_inputs])

Wx=tf.Variable(tf.random_normal(shape=[n_inputs,n_neurons],dtype=tf.float32))
Wy=tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b=tf.Variable(tf.zeros([1,n_neurons],dtype=tf.float32))

Y0=tf.tanh(tf.matmul(X0,Wx)+b)
Y1=tf.tanh(tf.matmul(Y0,Wy)+tf.matmul(X1,Wx)+b)

init=tf.global_variables_initializer()

In [38]:
X0_batch=np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch=np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])

with tf.Session() as sess:
    init.run()
    Y0_val,Y1_val=sess.run([Y0,Y1],feed_dict={X0:X0_batch,X1:X1_batch})
print(Y0_val)
print(Y1_val)

[[-0.9999943  -0.9996731  -0.99978876 -0.6449286  -0.73387307]
 [-1.         -1.         -1.         -0.97668684 -0.5368581 ]
 [-1.         -1.         -1.         -0.99871194 -0.25653195]
 [-0.5433824  -0.99983     0.9900181  -0.9998961   1.        ]]
[[-1.         -1.         -1.         -0.9931061   0.8955367 ]
 [ 0.80734116  0.2728058  -0.98870987  0.6121636  -0.34634364]
 [-1.         -0.9999999  -1.         -0.83637804  0.85485244]
 [-0.9998076  -0.9989798  -0.99968255 -0.98200065  0.84972316]]
