In [1]:
import tensorflow as tf
import numpy as np
from tf_graph import show_graph

In [2]:
n_inputs=3
n_neurons=5
X0=tf.placeholder(tf.float32,[None,n_inputs])
X1=tf.placeholder(tf.float32,[None,n_inputs])

Wx=tf.Variable(tf.random_normal(shape=[n_inputs,n_neurons],dtype=tf.float32))
Wy=tf.Variable(tf.random_normal(shape=[n_neurons,n_neurons],dtype=tf.float32))
b=tf.Variable(tf.zeros([1,n_neurons],dtype=tf.float32))

Y0=tf.tanh(tf.matmul(X0,Wx)+b)
Y1=tf.tanh(tf.matmul(Y0,Wy)+tf.matmul(X1,Wx)+b)

init=tf.global_variables_initializer()

In [3]:
X0_batch=np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch=np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])

In [4]:
with tf.Session() as sess:
    init.run()
    Y0_val,Y1_val=sess.run([Y0,Y1],feed_dict={X0:X0_batch,X1:X1_batch})
print(Y0_val)
print(Y1_val)

[[ 0.38402843  0.99853474  0.9972077   0.84937024  0.7050371 ]
 [-0.42651856  1.          1.          0.9997066   0.9999682 ]
 [-0.86579645  1.          1.          0.99999946  1.        ]
 [-0.9977272   1.          0.9997361  -0.83907413  0.99999934]]
[[-0.99961066  1.          1.          0.9999851   1.        ]
 [-0.9887484   0.569843    0.00121844 -0.99707973  0.31802997]
 [-0.99995613  1.          1.          0.8981654   1.        ]
 [-0.99952674  0.9999794   0.99977463 -0.90323     0.9993766 ]]


In [5]:
show_graph(tf.get_default_graph().as_graph_def())

In [6]:
tf.reset_default_graph()
init_g = tf.global_variables_initializer()
init_l = tf.local_variables_initializer()
X0=tf.placeholder(tf.float32,[None,n_inputs])
X1=tf.placeholder(tf.float32,[None,n_inputs])
basic_cell=tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,)
output_seqs,states=tf.contrib.rnn.static_rnn(basic_cell,[X0,X1],dtype=tf.float32)
output=tf.stack(output_seqs)
X0_batch=np.array([[0,1,2],[3,4,5],[6,7,8],[9,0,1]])
X1_batch=np.array([[9,8,7],[0,0,0],[6,5,4],[3,2,1]])
# show_graph(tf.get_default_graph().as_graph_def())
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    output_val=output.eval(feed_dict={X0:X0_batch,X1:X1_batch})
print(output_val)

Instructions for updating:
Use the retry module or similar alternatives.
[[[ 0.8982751   0.13669242  0.24759085  0.24150218  0.60966057]
  [ 0.9999603  -0.59632057  0.86346674 -0.92920655  0.669117  ]
  [ 1.         -0.9073621   0.9823544  -0.9983559   0.7210862 ]
  [ 0.9996847  -0.99999136  0.489204   -0.99986637 -0.99996513]]

 [[ 1.         -0.9936174   0.99681896 -0.9999644   0.19164616]
  [-0.6048845  -0.3723103   0.00812708  0.59437084  0.47884467]
  [ 0.99996686 -0.9727112   0.951477   -0.99809575  0.0190073 ]
  [ 0.91502976 -0.93036044  0.8285678  -0.9134482  -0.73217016]]]


In [8]:
X_batch=np.array(list(zip(X0_batch,X1_batch)))
tf.reset_default_graph()
n_steps=2
X=tf.placeholder(tf.float32,[None,n_steps,n_inputs])
X_seqs=tf.unstack(tf.transpose(X,perm=[1,0,2])) # unpack to list along first dimension (steps)
basic_cell=tf.contrib.rnn.BasicRNNCell(num_units=n_neurons,)
output_seqs,states=tf.contrib.rnn.static_rnn(basic_cell,X_seqs,dtype=tf.float32)
outputs=tf.transpose(tf.stack(output_seqs),perm=[1,0,2]) #stack: list to array (default: along first dimension)
# outputs=tf.transpose(tf.stack(output_seqs),perm=[0,1,2]) # time,instances,inputs
outputs=tf.transpose(tf.stack(output_seqs),perm=[1,0,2]) # instance,time,inputs
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    outputs_val=outputs.eval(feed_dict={X:X_batch})
print(outputs_val)

[[[-0.8499689   0.5075415  -0.65404606  0.9149936   0.86482584]
  [-0.9999921   0.9982907  -0.9014893   1.          0.9999999 ]]

 [[-0.99841547  0.95740896 -0.9238156   0.9999854   0.99973226]
  [-0.7005779   0.01530349  0.4635964   0.08050765  0.5280449 ]]

 [[-0.9999845   0.9971054  -0.98511606  1.          0.9999996 ]
  [-0.99961805  0.97527254 -0.3433382   0.9999989   0.9999725 ]]

 [[-0.97346514  0.9992248  -0.04626949  0.9989505   0.999078  ]
  [-0.9261889   0.30776113  0.48662922  0.9943239   0.94932836]]]
