In [1]:
import numpy as np

In [2]:
a=np.random.randn(5)

In [3]:
a


array([-0.07923167, -0.37486537,  0.99997045, -2.42054561,  0.92450795])

In [4]:
expa=np.exp(a)

In [6]:
expa

array([ 0.92382588,  0.68738181,  2.71820151,  0.08887311,  2.52062767])

In [8]:
answer=expa/expa.sum()

In [10]:
answer

array([ 0.13313703,  0.09906193,  0.39173321,  0.01280794,  0.36325989])

In [11]:
answer.sum()

0.99999999999999989

In [13]:
A=np.random.randn(100,5)

In [15]:
A

array([[  1.23463552e+00,  -5.97649583e-01,   7.15597880e-01,
          9.96405015e-02,  -5.01849650e-01],
       [  5.54689269e-02,  -6.11130658e-01,  -5.55042016e-02,
          1.19438445e+00,   6.95254331e-01],
       [  5.77178396e-01,   1.34685955e+00,   4.23742960e-01,
          1.52954596e+00,  -1.53461924e+00],
       [ -5.89650171e-01,   1.03099359e+00,   3.16148339e-01,
         -9.85675866e-02,  -7.40771995e-01],
       [  7.21923553e-01,  -1.42336620e+00,   2.38312633e-01,
          1.17708178e+00,  -1.71813113e+00],
       [ -2.43460556e-01,  -1.50340199e+00,  -9.83414917e-01,
          6.97596267e-01,   1.12111491e+00],
       [  3.79455485e-01,   5.20853501e-01,  -3.41323429e-01,
         -5.69191166e-01,   1.53946671e-01],
       [  7.06606114e-01,  -8.68640429e-01,   6.44580633e-01,
          1.31857746e+00,  -6.64439451e-01],
       [  2.12457205e-01,   7.72177552e-03,   1.66508532e-01,
         -1.40303646e+00,   1.07007514e+00],
       [ -4.53701728e-01,  -4.8734252

In [16]:
expA=np.exp(A)
expA

array([[  3.43712554,   0.55010309,   2.04540923,   1.10477368,
          0.60540983],
       [  1.05703617,   0.54273687,   0.94600805,   3.3015249 ,
          2.00421874],
       [  1.78100604,   3.84533047,   1.52766887,   4.61608045,
          0.21553774],
       [  0.55452124,   2.80385033,   1.37183374,   0.90613445,
          0.47674573],
       [  2.05838883,   0.24090173,   1.26910589,   3.24489106,
          0.17940111],
       [  0.7839104 ,   0.22237236,   0.37403163,   2.008918  ,
          3.06827314],
       [  1.46148857,   1.68346387,   0.71082897,   0.56598304,
          1.16642868],
       [  2.02709983,   0.41952153,   1.90518789,   3.7381    ,
          0.51456188],
       [  1.23671319,   1.00775167,   1.18117361,   0.24584932,
          2.91559857],
       [  0.63527219,   0.6142566 ,   0.64385181,   0.92981972,
          1.40421191],
       [  0.66526006,   0.13097632,   0.33871888,   0.81220739,
          0.44033542],
       [  0.87609709,   3.40389601,   1.248

In [20]:
expA.sum(axis=1,keepdims=True) # keep it as an column matrix

array([[  7.74282137],
       [  7.85152474],
       [ 11.98562358],
       [  6.11308548],
       [  6.99268862],
       [  6.45750552],
       [  5.58819313],
       [  8.60447113],
       [  6.58708635],
       [  4.22741222],
       [  2.38749808],
       [ 11.14720021],
       [ 12.36287255],
       [  7.05800133],
       [  6.40913617],
       [  7.01082454],
       [ 12.4922562 ],
       [  9.16598636],
       [  3.69805975],
       [ 11.56555117],
       [  3.19689176],
       [ 17.79045749],
       [ 36.90911315],
       [  9.3866091 ],
       [  4.61889425],
       [  5.91367343],
       [  6.29546829],
       [ 21.5237714 ],
       [ 10.12825335],
       [  6.82855682],
       [ 10.89039835],
       [ 10.93382089],
       [  4.44029393],
       [  4.39620472],
       [ 15.50623965],
       [ 14.10960041],
       [  8.3767547 ],
       [  7.55350195],
       [  4.76383021],
       [  4.30159801],
       [  3.5811294 ],
       [ 10.06778333],
       [ 13.4953526 ],
       [  4

In [21]:
answer=expA/expA.sum(axis=1,keepdims=True) 
answer

array([[ 0.44391125,  0.07104685,  0.26416846,  0.14268361,  0.07818982],
       [ 0.13462814,  0.06912503,  0.12048718,  0.42049475,  0.25526491],
       [ 0.14859519,  0.32082857,  0.12745844,  0.38513478,  0.01798302],
       [ 0.09071053,  0.45866369,  0.22440938,  0.14822866,  0.07798774],
       [ 0.294363  ,  0.03445052,  0.18149041,  0.46404055,  0.02565553],
       [ 0.12139523,  0.03443626,  0.057922  ,  0.31109815,  0.47514836],
       [ 0.26153151,  0.3012537 ,  0.12720193,  0.10128194,  0.20873092],
       [ 0.2355868 ,  0.04875623,  0.22141836,  0.43443693,  0.05980169],
       [ 0.18774814,  0.15298899,  0.17931655,  0.03732292,  0.4426234 ],
       [ 0.15027448,  0.14530322,  0.152304  ,  0.21995009,  0.3321682 ],
       [ 0.27864318,  0.05485924,  0.1418719 ,  0.34019185,  0.18443383],
       [ 0.07859347,  0.30535883,  0.1119723 ,  0.11276153,  0.39131387],
       [ 0.03413443,  0.21202143,  0.03931428,  0.70294062,  0.01158924],
       [ 0.28181518,  0.03678825,  0.0

In [22]:
answer.sum(axis=1,keepdims=True)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      